### PR TITLE
Demonstration of how to Backpack'ify this package.

### PR DESCRIPTION
**Pull request by ezyang**
In this Reddit thread
https://www.reddit.com/r/haskell/comments/28v6c9/backpack_an_mllike_module_system_for_haskell/cif36ed
@chrisdone mentioned tagstream-conduit as an example of a place where
lack of parametrized modules made it a bit annoying to write
entity parsing code that worked for both Text and ByteString.

In this commit, I give a refactoring of tagstream-conduit which
uses Backpack to handle parametrization. The key component,
entities/Entities.hs, is parametrized over the
type of String, Builder and Parser you want to use.  This
eliminates the duplication between Text/HTML/TagStream/ByteString.hs
and Text/HTML/TagStream/Text.hs, which are now just reexports of
appropriately instantiated versions of Entities.

There are three internal libraries:

```
- 'types' defines common data types and "shim" modules for
  ByteString and Text.  (If I can convince text/bytestring
  to standardize naming for all their functions, I can
  reduce/eliminate these shim modules.)
- 'entities' is the parametrized component, parametrized
  over the Str, Builder and Parser modules (the signatures
  required for these modules are in the hsig files.)
- 'tagstream-conduit' is the main library and exposes the
  same outward facing interface as the old library.
```

Please take a look at the refactoring and let me know how you
like it; unfortunately, you'll need my development branches of
Cabal and GHC to actually build this package. In
particular, supposing that Backpack was supported on all
the versions of GHC/Cabal you wanted to target, would you
use this? What do you like/dislike about the system?

Signed-off-by: Edward Z. Yang ezyang@cs.stanford.edu

### CODE REVIEW

**Comment by ezyang** [comment]
(You may find it easier to review the full tree at https://github.com/ezyang/tagstream-conduit rather than the diff.)

**Comment by yihuang** [comment]
Thanks for your efforts, it looks interesting, but I guess I need to know more about backpack to comment.
Do you expect to merge this into master and release on hackage now? Or it's just experimental.

**Comment by ezyang** [comment]
Oh you can't build this code with any released version of GHC ;) So definitely wouldn't merge.

**Comment by ibotty** [comment]
I certainly like it.

Is it possible to separate out tagstream-conduit-text into its own package? If so, might you include it in this pull request?

**Comment by ezyang** [comment]
Yes, definitely. It's mostly the "obvious" thing, would have to get Backpack working on cabal-install though ;)

**Comment by ezyang** [comment]
FWIW, Backpack in cabal-install is now working

**Comment by ezyang** [comment]
@yihuang Uh, you probably didn't want to merge this. Happy to close this PR if you are trying to keep the PR queue tidy.

**Comment by yihuang** [comment]
@ezyang Why not, isn't this works on ghc8.2? I'm ready to try backpack on new ghc and cabal.

**Comment by ezyang** [comment]
Well, yes, but it will also mean that tagstream-conduit won't work with old versions of GHC. (But if you're up for it, hooray! It might be a good idea for us to make use of str-sig which post-dates this PR I made http://next.hackage.haskell.org:8080/package/str-sig-0.1.0.0)

**Pull request merged**
